# Generated by Django 4.0.2 on 2022-03-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familya')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('position', models.CharField(max_length=150)),
                ('data_of_birth', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Profile_Pic/%Y/%m/%d/', verbose_name='Foydalanuvchi rasmi')),
            ],
        ),
    ]
