# Generated by Django 4.0.2 on 2022-03-11 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=15, validators=[django.core.validators.MinLengthValidator(4)]),
            preserve_default=False,
        ),
    ]
