# Generated by Django 4.0.2 on 2022-03-11 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
