# Generated by Django 4.0.2 on 2022-02-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('smartfon', 'Smartfon'), ('telefon', 'Telefon'), ('computer', 'Copmuter'), ('planshet', 'Planshet'), ('noutbook', 'Noutbook'), ('smartwatch', 'SmartWatch')], max_length=150, verbose_name='Mahsulot turi')),
                ('nom', models.CharField(max_length=150, verbose_name='Mahsulot nomi')),
                ('rang', models.CharField(choices=[('qora', 'Qora'), ('oq', 'Oq'), ('qizil', 'Qizil'), ('sariq', 'Sariq'), ('kulrang', 'Kulrang'), ('moviy', 'Moviy'), ('yashil', 'Yashil'), ('jigarang', 'Jigarang'), ('pushti', 'Pushti'), ('boshqa', 'Boshqa')], max_length=50)),
                ('rasm', models.ImageField(upload_to='mahsulotlar/%Y/%m/%d/')),
                ('son', models.IntegerField(default=0)),
                ('kompania', models.CharField(choices=[('kompania', 'Ishlab chiqaruvchi nomi')], default='kompania', max_length=200)),
                ('mudat', models.CharField(choices=[('x', ''), ('0', 'cheklanmagan'), ('1/2', '6 oy'), ('1', ' 1 yil'), ('2', '2 yil'), ('3', '3 yil'), ('5', '5 yil'), ('10', '10 yil')], default='x', max_length=150)),
                ('kg', models.IntegerField(default=0)),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
