# Generated by Django 4.0.2 on 2022-03-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('smartfon', 'Smartfon'), ('telefon', 'Telefon'), ('computer', 'Copmuter'), ('planshet', 'Planshet'), ('noutbook', 'Noutbook'), ('smartwatch', 'SmartWatch')], max_length=150, verbose_name='Mahsulot turi')),
                ('nom', models.CharField(max_length=150, verbose_name='Mahsulot nomi')),
                ('rang', models.CharField(blank=True, choices=[('qora', 'Qora'), ('oq', 'Oq'), ('qizil', 'Qizil'), ('sariq', 'Sariq'), ('kulrang', 'Kulrang'), ('moviy', 'Moviy'), ('yashil', 'Yashil'), ('jigarang', 'Jigarang'), ('pushti', 'Pushti'), ('boshqa', 'Boshqa')], max_length=50, null=True, verbose_name='Mahsulot rangi')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='mahsulotlar/%Y/%m/%d/', verbose_name='Mahsulot rasmi')),
                ('narx', models.IntegerField(blank=True, default=0, null=True, verbose_name='Mahsulot natxi($)')),
                ('son', models.IntegerField(blank=True, default=0, null=True, verbose_name='Mahsulot soni')),
                ('kompania', models.CharField(blank=True, choices=[('kompania', 'Ishlab chiqaruvchi nomi')], default='kompania', max_length=200, null=True, verbose_name='Ishlab chiqaruvchi nomi ')),
                ('mudat', models.CharField(blank=True, choices=[('x', ''), ('0', 'cheklanmagan'), ('1/2', '6 oy'), ('1', ' 1 yil'), ('2', '2 yil'), ('3', '3 yil'), ('5', '5 yil'), ('10', '10 yil')], default='x', max_length=150, null=True, verbose_name='Yaroqlilik mudati')),
                ('kg', models.IntegerField(blank=True, default=0, null=True, verbose_name="Mahsulot og'irligi(kg)")),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='QR_codes/%Y/%m/%d/', verbose_name='Mahsulot QR codi')),
                ('izoh', models.CharField(blank=True, max_length=300, null=True, verbose_name="Qo'shimcha izoh")),
                ('sana', models.DateField(verbose_name='Omborga kelgan sana')),
                ('yangilanish', models.DateTimeField(auto_now=True, verbose_name="O'zgartirish kiritilgan sana")),
            ],
        ),
    ]
