# Generated by Django 4.0.2 on 2022-03-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='sh_code',
            field=models.ImageField(blank=True, null=True, upload_to='Shtrx_codes/%Y/%m/%d/', verbose_name='Mahsulot Shtrx codi'),
        ),
    ]
