# Generated by Django 4.0.2 on 2022-02-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='narx',
            field=models.IntegerField(default=0, verbose_name='Mahsulot natxi'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='kg',
            field=models.IntegerField(default=0, verbose_name="Mahsulot og'irligi"),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='kompania',
            field=models.CharField(choices=[('kompania', 'Ishlab chiqaruvchi nomi')], default='kompania', max_length=200, verbose_name='Ishlab chiqaruvchi nomi '),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='mudat',
            field=models.CharField(choices=[('x', ''), ('0', 'cheklanmagan'), ('1/2', '6 oy'), ('1', ' 1 yil'), ('2', '2 yil'), ('3', '3 yil'), ('5', '5 yil'), ('10', '10 yil')], default='x', max_length=150, verbose_name='Yaroqlilik mudati'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='rang',
            field=models.CharField(choices=[('qora', 'Qora'), ('oq', 'Oq'), ('qizil', 'Qizil'), ('sariq', 'Sariq'), ('kulrang', 'Kulrang'), ('moviy', 'Moviy'), ('yashil', 'Yashil'), ('jigarang', 'Jigarang'), ('pushti', 'Pushti'), ('boshqa', 'Boshqa')], max_length=50, verbose_name='Mahsulot rangi'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='rasm',
            field=models.ImageField(upload_to='mahsulotlar/%Y/%m/%d/', verbose_name='Mahsulot rasmi'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='sana',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ishlab chiqarilgan sana'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='son',
            field=models.IntegerField(default=0, verbose_name='Mahsulot soni'),
        ),
    ]
