# Generated by Django 4.0.2 on 2022-03-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_mahsulot_sh_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahsulot',
            old_name='sh_code',
            new_name='shcode',
        ),
    ]
