# Generated by Django 4.0.2 on 2022-02-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_mahsulot_yangilanish_alter_mahsulot_narx'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='qr_code',
            field=models.ImageField(default=1, upload_to='QR_codes/%Y/%m/%d/', verbose_name='Mahsulot QR codi'),
            preserve_default=False,
        ),
    ]
