# Generated by Django 4.0.2 on 2022-03-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_sh_code_mahsulot_shcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulot',
            name='shcode',
        ),
    ]
