# Generated by Django 4.0.2 on 2022-03-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_costomuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costomuser',
            name='user',
        ),
    ]
