# Generated by Django 4.0.2 on 2022-02-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_mahsulot_kg_alter_mahsulot_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='kg',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Mahsulot og'irligi(kg)"),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='kompania',
            field=models.CharField(blank=True, choices=[('kompania', 'Ishlab chiqaruvchi nomi')], default='kompania', max_length=200, null=True, verbose_name='Ishlab chiqaruvchi nomi '),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='mudat',
            field=models.CharField(blank=True, choices=[('x', ''), ('0', 'cheklanmagan'), ('1/2', '6 oy'), ('1', ' 1 yil'), ('2', '2 yil'), ('3', '3 yil'), ('5', '5 yil'), ('10', '10 yil')], default='x', max_length=150, null=True, verbose_name='Yaroqlilik mudati'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='narx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Mahsulot natxi($)'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='rang',
            field=models.CharField(blank=True, choices=[('qora', 'Qora'), ('oq', 'Oq'), ('qizil', 'Qizil'), ('sariq', 'Sariq'), ('kulrang', 'Kulrang'), ('moviy', 'Moviy'), ('yashil', 'Yashil'), ('jigarang', 'Jigarang'), ('pushti', 'Pushti'), ('boshqa', 'Boshqa')], max_length=50, null=True, verbose_name='Mahsulot rangi'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='mahsulotlar/%Y/%m/%d/', verbose_name='Mahsulot rasmi'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='son',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Mahsulot soni'),
        ),
    ]
