# Generated by Django 4.0.2 on 2022-03-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_costomuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costomuser',
            name='position',
        ),
    ]
