# Generated by Django 4.0.2 on 2022-03-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_costomuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='costomuser',
            name='position',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
